name: cedalion
channels:
  - conda-forge
dependencies:
  - black=23.7.0
  - click=8.1.3
  - flake8=6.0.0
  - h5py=3.8.0
  - ipython=8.13.2
  - jupyter
  - matplotlib=3.7.1
  - nibabel=5.1.0
  - nilearn=0.10.0
  - nipype=1.8.6
  - notebook=6.5.4
  - numpy=1.23.5
  - opencv=4.6.0
  - pandas=2.0.1
  - pint-xarray=0.3
  - pip=23.1.2
  - pooch=1.7.0
  - pre_commit=3.3.3
  - pybids=0.16.1
  - pylint=2.17.5
  - pytest=7.3.1
  - pytest-cov=4.0.0
  - python=3.10
  - pywavelets=1.4.1
  - ruff=0.0.285
  - scikit-image=0.20.0
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - seaborn=0.12.2
  - statsmodels=0.13.5
  - strenum=0.4.15
  - xarray=2024.2.0
  - cudatoolkit
  - trimesh
  - pyvista
  - trame
  - vtk=9.2.2

  - nbsphinx=0.9.3
  - nbstripout=0.7.1
  - sphinx
  - myst-parser
  - sphinx-autodoc-typehints
  - sphinx_rtd_theme

  - pip:
      - mne==1.4.0
      - mne-bids==0.12
      - mne-nirs==0.5.0
      - pywavefront==1.3.3
      - setuptools-scm==7.1.0
      - snirf==0.7.4
      - pmcx
      - open3d==0.16
